# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'nimble-ios-technical-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nimble-ios-technical-test
  pod 'Alamofire'
  pod 'lottie-ios'

end
